name: 'spotifyDbtData'
version: '1.0.0'

profile: 'spotifyDbtData'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotifyDbtData:
    +post-hook: "grant all privileges on {{ this }} to analytics_user"
    
    example:
      +materialized: view

    staging:
      +materialized: table
      +schema: staging
      +post-hook: "grant all privileges on {{ this }} to analytics_user"

    intermediate:
      +materialized: table
      +schema: intermediate
      +post-hook: "grant all privileges on {{ this }} to dbt_ro_user"

    bridge:
      +materialized: table
      +schema: bridge
      +post-hook: "grant all privileges on {{ this }} to analytics_user"

    dim:
      +materialized: table
      +schema: dim
      +post-hook: "grant all privileges on {{ this }} to analytics_user"

    fact:
      +materialized: table
      +schema: fact
      +post-hook: "grant all privileges on {{ this }} to analytics_user"
